/**
 * @author Eric Dunbar
 * @date 7/7/2016
 * @assignment 1
 * @question 2A
 * @title Demonstrates SLList node swapping
 * @description Demonstrates the node swapping operation for a singly-linked list.
 * 
 */
public class Q2ASLListSwappingDemo {
	static TestSuite theTester;

	/**
	 * Swap the nodes in a singly-linked-list in a forward or reverse direction (starting at node 0
	 * or the last node) and proceeding until all nodes have been swapped. The starting node should
	 * be moved to the other end of the linked list if the SLList is implemented correctly.
	 * 
	 * @param forward true if swapping happens left(node 0)-to-right(tail node)
	 * @param errorOffset 0, error free operation, +1 should cause IndexOutOfBoundException
	 */
	private static void swapNodeDemo(boolean forward, int errorOffset) {
		SLList<String> mySwapQueue = new SLList<>();

		String[] ordinals = { "Ten", "One", "Two", "Three", "Four", "Five", "Six", "Seven", "Eight", "Nine" };

		String[] description = { "",
				"Initial list: The 'Ten' is out of logical order when initially added to SLList." };

		for (String string : description) {
			System.out.println(string);
		}
		if (forward)
			System.out.printf("   Operation: Each Node has been swapped, starting at 0 and ending at size()-%d%n",
					2 - errorOffset);
		else
			System.out.printf("   Operation: Each Node has been swapped, starting at size()-%d and ending at 0%n",
					2 - errorOffset);

		System.out.println();
		for (int j = 0; j < 1; j++) {
			for (int i = 0; i < ordinals.length; i++) {
				String s = ordinals[i];// + (1 - j);
				mySwapQueue.add(s);
			}
		}

		System.out.print("   Node:");
		for (int idx = 0; idx < mySwapQueue.size(); idx++) {
			System.out.printf("%5d ", idx);
		}

		System.out.println();

		System.out.print("Initial: ");
		for (int idx = 0; idx < mySwapQueue.size(); idx++) {
			System.out.printf("%5s ", mySwapQueue.getNode(idx).elementData);
		}

		System.out.println();

		if (forward) {
			for (int i = 0; i < mySwapQueue.size() - 1 + errorOffset; i++) {
				mySwapQueue.swapWithNextNode(mySwapQueue.getNode(i));
			}
		} else {
			for (int i = mySwapQueue.size() - 2 + errorOffset; i >= 0; i--) {
				mySwapQueue.swapWithNextNode(mySwapQueue.getNode(i));
			}
		}

		System.out.print("  Final: ");
		for (int idx = 0; idx < mySwapQueue.size(); idx++) {
			System.out.printf("%5s ", mySwapQueue.getNode(idx).elementData);
		}

		System.out.println();
	}

	public static void main(String[] args) {
		// Are we testing?
		boolean testing = false;

		// Display programmer info and create testing object
		theTester = CommonSuite.commonProgramStart("1", "2a", "Singly-linked List Swap Demo", testing);
		theTester.setSilentRecording(false); // report results immediately

		// Display tasks
		String[] tasksList = { "1. Test link swapping (forward)", "2. Test link swapping (reverse)",
				"3. Test link swapping exceptions generated by invalid indices" };

		int currentTask = 0;

		System.out.println("TASKS:");
		CommonSuite.printlnIndentArray(tasksList);

		// perform the tasks required by the question
		// TASK 1.

		CommonSuite.headerPrint(tasksList, currentTask++);
		swapNodeDemo(true, 0);

		// perform the tasks required by the question
		// TASK 2.

		CommonSuite.headerPrint(tasksList, currentTask++);
		swapNodeDemo(false, 0);

		// perform the tasks required by the question
		// TASK 3.

		CommonSuite.headerPrint(tasksList, currentTask++);
		try {
			swapNodeDemo(true, 1);
			System.out.println("ERROR. Exception expected. Code did not perform as expected.");
		} catch (IndexOutOfBoundsException e) {
			System.out.println("Success. Exception expected. Code performs as expected");
			System.out.println("         " + e);
		}

		CommonSuite.commonProgramEnd(theTester);
	}
}
